version: "3"
services:
  # ===================================nginx-proxy-manager===================================
  nginx_proxy_manger:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/HDD/AppsData/nginx_proxy_manger/data:/data
      - /mnt/HDD/AppsData/nginx_proxy_manger/etc/letsencrypt:/etc/letsencrypt
    networks:
      - main_network
networks:
  main_network:
    external: true
