version: "3"

services:
  portainer:
    image: portainer/portainer-ce:linux-arm
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/HDD/AppsData/portainer/data:/data
    networks:
      - main_network

networks:
  main_network:
    external: true
