version: '3.3'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    # network_mode: host  # Use host network mode for better performance
    volumes:
      - /mnt/AppsData/jellyfin/config:/config
      - /mnt/HDD/Media:/media
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: always
    networks:
      - main_network
networks:
  main_network:
    external: true

