version: '3.3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /mnt/HDD:/srv
      - /mnt/HDD/AppsData/FileBrowser/filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9090:80
    restart: always
    networks:
      - main_network

networks:
  main_network:
    external: true
