version: "2"

services:
  gitea:
    image: strobi/rpi-gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /mnt/HDD/AppsData/gitea/data:/data
    ports:
      - "3020:3000"
      - "2200:22"
    networks:
      - main_network
networks:
  main_network:
    external: true
