version: "3.7"
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - APP_TIMEZONE=Africa/Cairo
      - DISPLAY_TIMEZONE=Africa/Cairo
      - SPEEDTEST_SCHEDULE=*/50 * * * *
      - APP_KEY=base64:DZnrZk7OCrb/NnyNKCGQnyySLiIgIajhLWnLtZ1EBUg=
      - APP_URL=http://speed.home.local/
      - DB_CONNECTION=sqlite
    volumes:
      - /mnt/HDD/AppsData/speedtest-tracker/config:/config
    ports:
      - 8034:80
      - 8443:443
    restart: unless-stopped
    networks:
      - main_network

networks:
  main_network:
    external: true
