---
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 67:68/tcp
      - 69:68/udp
      - 853:853/tcp
      - 85:80/tcp #change this to something like 81:80 if port 80 is already in use
      - 3000:3000/tcp
    volumes:
      - /mnt/HDD/AppsData/adguardhome/opt/adguardhome/work:/opt/adguardhome/work
      - /mnt/HDD/AppsData/adguardhome/opt/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - main_network
networks:
  main_network:
    external: true
