---
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/AppsData/emby:/config
      - /mnt/HDD/Media:/Media
    ports:
      - 8097:8096
      - 8920:8920 #optional
    networks:
      - main_network
    restart: unless-stopped

networks:
  main_network:
    external: true
