version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/HDD/AppsData/portianer/data:/data
    networks:
      - main_network
networks:
  main_network:
    external: true
volumes:
  portainer_data: