version: "2.1"
services:
  prowlarr:
    image: linuxserver/prowlarr:arm64v8-latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    volumes:
      - /mnt/HDD/AppsData/prowlarr/config:/config
    restart: unless-stopped
    ports:
      - 9696:9696
    networks:
      - main_network
networks:
  main_network:
    external: true
